using System.Diagnostics.CodeAnalysis;

// The only purpose of this file is to add ExcludeFromCodeCoverage attribute to the autogenerated service classes
// These produce a lot of code that will skew the coverage results


// ReSharper disable once CheckNamespace
namespace Helsenorge.Registries.AddressService
{
    [ExcludeFromCodeCoverage]
    internal partial class CommunicationPartySearch
    {

    }

    [ExcludeFromCodeCoverage]
    internal partial class SearchResult
    {

    }

    [ExcludeFromCodeCoverage]
    internal partial class SearchFacet
    {

    }

    [ExcludeFromCodeCoverage]
    internal partial class CommunicationParty
    {

    }

    [ExcludeFromCodeCoverage]
    internal partial class SearchResultFacetEntry
    {

    }
    [ExcludeFromCodeCoverage]
    internal partial class Code
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class Period
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class Organization
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class Department
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class OrganizationPerson
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class Service
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class ElectronicAddress
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class PhysicalAddress
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class Person
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class CitizenId
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class HPRInformation
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class Authorization
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class SpecialCompetence
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class Requisition
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class Speciality
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class GenericFault
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class OrganizationPersonUpdate
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class ValidationFault
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class ValidationError
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class ServiceUpdate
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class OrganizationUpdate
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class DepartmentUpdate
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class OrganizationPersonCreate
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class ServiceCreate
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class OrganizationCreate
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class DepartmentCreate
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class EntityLogEntry
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class EntityLogEntryData
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class CommunicationPartyStatistics
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class BusinessTypeStatistics
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class OrganizationUpdateStatistics
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class UpdateStatistic
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class CertificateDetails
    {
    }

    [ExcludeFromCodeCoverage]
    internal partial class CommunicationPartyServiceClient
    {
    }
}

namespace Helsenorge.Registries.CPAService
{
    [ExcludeFromCodeCoverage]
    internal partial class CollaborationProtocolProfile
    {
    }
    [ExcludeFromCodeCoverage]
    internal partial class PartyInfo {
    }
    [ExcludeFromCodeCoverage]
    internal partial class Certificate {
    }
    [ExcludeFromCodeCoverage]
    internal partial class DeliveryChannel {
    }
    [ExcludeFromCodeCoverage]
    internal partial class CollaborationRole {
    }
    [ExcludeFromCodeCoverage]
    internal partial class Code {
    }
    [ExcludeFromCodeCoverage]
    internal partial class RetrySettings {
    }
    [ExcludeFromCodeCoverage]
    internal partial class ProcessSpecification {
    }
    [ExcludeFromCodeCoverage]
    internal partial class Message {
    }
    [ExcludeFromCodeCoverage]
    internal partial class ChannelMessagesCombination {
    }
    [ExcludeFromCodeCoverage]
    internal partial class GenericFault {
    }
    [ExcludeFromCodeCoverage]
    internal partial class CollaborationProtocolProfileParameters {
    }
    [ExcludeFromCodeCoverage]
    internal partial class Process {
    }
    [ExcludeFromCodeCoverage]
    internal partial class Channel {
    }
    [ExcludeFromCodeCoverage]
    internal partial class Role {
    }
    [ExcludeFromCodeCoverage]
    internal partial class CpaDetails {
    }
    [ExcludeFromCodeCoverage]
    internal partial class CollaborationProtocolAgreement {
    }
    [ExcludeFromCodeCoverage]
    internal partial class CpaXmlDetails {
    }
    [ExcludeFromCodeCoverage]
    internal partial class CollaborationRoleIdentifier {
    }
    [ExcludeFromCodeCoverage]
    internal partial class ProcessParameter {
    }
    [ExcludeFromCodeCoverage]
    internal partial class CPPAServiceClient
    {
    }
}

