//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS0108

namespace Helsenorge.Registries.CPAService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CollaborationProtocolProfile", Namespace="http://schemas.nhn.no/reg/CollaborationProtocolProfile")]
    internal partial class CollaborationProtocolProfile : object
    {
        
        private System.Nullable<System.Guid> IdField;
        
        private Helsenorge.Registries.CPAService.PartyInfo PartyInfoField;
        
        private System.DateTime ValidFromField;
        
        private System.DateTime ValidToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Helsenorge.Registries.CPAService.PartyInfo PartyInfo
        {
            get
            {
                return this.PartyInfoField;
            }
            set
            {
                this.PartyInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ValidFrom
        {
            get
            {
                return this.ValidFromField;
            }
            set
            {
                this.ValidFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ValidTo
        {
            get
            {
                return this.ValidToField;
            }
            set
            {
                this.ValidToField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartyInfo", Namespace="http://schemas.nhn.no/reg/CollaborationProtocolProfile")]
    internal partial class PartyInfo : object
    {
        
        private int HerIdField;
        
        private string PartyNameField;
        
        private Helsenorge.Registries.CPAService.Certificate[] CertificatesField;
        
        private Helsenorge.Registries.CPAService.DeliveryChannel[] DeliveryChannelsField;
        
        private Helsenorge.Registries.CPAService.CollaborationRole[] CollaborationRolesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HerId
        {
            get
            {
                return this.HerIdField;
            }
            set
            {
                this.HerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartyName
        {
            get
            {
                return this.PartyNameField;
            }
            set
            {
                this.PartyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public Helsenorge.Registries.CPAService.Certificate[] Certificates
        {
            get
            {
                return this.CertificatesField;
            }
            set
            {
                this.CertificatesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Helsenorge.Registries.CPAService.DeliveryChannel[] DeliveryChannels
        {
            get
            {
                return this.DeliveryChannelsField;
            }
            set
            {
                this.DeliveryChannelsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Helsenorge.Registries.CPAService.CollaborationRole[] CollaborationRoles
        {
            get
            {
                return this.CollaborationRolesField;
            }
            set
            {
                this.CollaborationRolesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Certificate", Namespace="http://schemas.nhn.no/reg/CollaborationProtocolProfile")]
    internal partial class Certificate : object
    {
        
        private string IdField;
        
        private byte[] X509CertificateRawDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] X509CertificateRawData
        {
            get
            {
                return this.X509CertificateRawDataField;
            }
            set
            {
                this.X509CertificateRawDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryChannel", Namespace="http://schemas.nhn.no/reg/CollaborationProtocolProfile")]
    internal partial class DeliveryChannel : object
    {
        
        private string AddressField;
        
        private Helsenorge.Registries.CPAService.Code ChannelTypeField;
        
        private string IdField;
        
        private Helsenorge.Registries.CPAService.RetrySettings RetrySettingsReceiverField;
        
        private Helsenorge.Registries.CPAService.RetrySettings RetrySettingsSenderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Helsenorge.Registries.CPAService.Code ChannelType
        {
            get
            {
                return this.ChannelTypeField;
            }
            set
            {
                this.ChannelTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Helsenorge.Registries.CPAService.RetrySettings RetrySettingsReceiver
        {
            get
            {
                return this.RetrySettingsReceiverField;
            }
            set
            {
                this.RetrySettingsReceiverField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Helsenorge.Registries.CPAService.RetrySettings RetrySettingsSender
        {
            get
            {
                return this.RetrySettingsSenderField;
            }
            set
            {
                this.RetrySettingsSenderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CollaborationRole", Namespace="http://schemas.nhn.no/reg/CollaborationProtocolProfile")]
    internal partial class CollaborationRole : object
    {
        
        private Helsenorge.Registries.CPAService.Message[] CanReceiveField;
        
        private Helsenorge.Registries.CPAService.Message[] CanSendField;
        
        private string EncryptionCertificateIdField;
        
        private System.Guid IdField;
        
        private Helsenorge.Registries.CPAService.ProcessSpecification ProcessSpecificationField;
        
        private string RoleNameField;
        
        private string SignatureCertificateIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Helsenorge.Registries.CPAService.Message[] CanReceive
        {
            get
            {
                return this.CanReceiveField;
            }
            set
            {
                this.CanReceiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Helsenorge.Registries.CPAService.Message[] CanSend
        {
            get
            {
                return this.CanSendField;
            }
            set
            {
                this.CanSendField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EncryptionCertificateId
        {
            get
            {
                return this.EncryptionCertificateIdField;
            }
            set
            {
                this.EncryptionCertificateIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Helsenorge.Registries.CPAService.ProcessSpecification ProcessSpecification
        {
            get
            {
                return this.ProcessSpecificationField;
            }
            set
            {
                this.ProcessSpecificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName
        {
            get
            {
                return this.RoleNameField;
            }
            set
            {
                this.RoleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignatureCertificateId
        {
            get
            {
                return this.SignatureCertificateIdField;
            }
            set
            {
                this.SignatureCertificateIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Code", Namespace="http://register.nhn.no/Common")]
    internal partial class Code : object
    {
        
        private bool ActiveField;
        
        private string CodeTextField;
        
        private string CodeValueField;
        
        private string LongDescriptionField;
        
        private int OIDField;
        
        private string SimpleTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active
        {
            get
            {
                return this.ActiveField;
            }
            set
            {
                this.ActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeText
        {
            get
            {
                return this.CodeTextField;
            }
            set
            {
                this.CodeTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeValue
        {
            get
            {
                return this.CodeValueField;
            }
            set
            {
                this.CodeValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LongDescription
        {
            get
            {
                return this.LongDescriptionField;
            }
            set
            {
                this.LongDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OID
        {
            get
            {
                return this.OIDField;
            }
            set
            {
                this.OIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SimpleType
        {
            get
            {
                return this.SimpleTypeField;
            }
            set
            {
                this.SimpleTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetrySettings", Namespace="http://schemas.nhn.no/reg/CollaborationProtocolProfile")]
    internal partial class RetrySettings : object
    {
        
        private string DocExchangeIdField;
        
        private System.Guid IdField;
        
        private string PersistDurationField;
        
        private int RetriesField;
        
        private string RetryIntervalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocExchangeId
        {
            get
            {
                return this.DocExchangeIdField;
            }
            set
            {
                this.DocExchangeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersistDuration
        {
            get
            {
                return this.PersistDurationField;
            }
            set
            {
                this.PersistDurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Retries
        {
            get
            {
                return this.RetriesField;
            }
            set
            {
                this.RetriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RetryInterval
        {
            get
            {
                return this.RetryIntervalField;
            }
            set
            {
                this.RetryIntervalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessSpecification", Namespace="http://schemas.nhn.no/reg/CollaborationProtocolProfile")]
    internal partial class ProcessSpecification : object
    {
        
        private Helsenorge.Registries.CPAService.ChannelMessagesCombination[] ChannelMessageCombinationsField;
        
        private string NameField;
        
        private string UuidField;
        
        private string VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Helsenorge.Registries.CPAService.ChannelMessagesCombination[] ChannelMessageCombinations
        {
            get
            {
                return this.ChannelMessageCombinationsField;
            }
            set
            {
                this.ChannelMessageCombinationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uuid
        {
            get
            {
                return this.UuidField;
            }
            set
            {
                this.UuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.nhn.no/reg/CollaborationProtocolProfile")]
    internal partial class Message : object
    {
        
        private string[] DeliveryChannelIdsField;
        
        private string IdField;
        
        private string NameField;
        
        private string OtherPartyMessageIdField;
        
        private string VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DeliveryChannelIds
        {
            get
            {
                return this.DeliveryChannelIdsField;
            }
            set
            {
                this.DeliveryChannelIdsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherPartyMessageId
        {
            get
            {
                return this.OtherPartyMessageIdField;
            }
            set
            {
                this.OtherPartyMessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChannelMessagesCombination", Namespace="http://schemas.nhn.no/reg/CollaborationProtocolProfile")]
    internal partial class ChannelMessagesCombination : object
    {
        
        private Helsenorge.Registries.CPAService.Code ChannelTypeField;
        
        private string[] MessageIdsField;
        
        private System.Guid RetrySettingsIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Helsenorge.Registries.CPAService.Code ChannelType
        {
            get
            {
                return this.ChannelTypeField;
            }
            set
            {
                this.ChannelTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] MessageIds
        {
            get
            {
                return this.MessageIdsField;
            }
            set
            {
                this.MessageIdsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RetrySettingsId
        {
            get
            {
                return this.RetrySettingsIdField;
            }
            set
            {
                this.RetrySettingsIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericFault", Namespace="http://register.nhn.no/Common")]
    internal partial class GenericFault : object
    {
        
        private string ErrorCodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CpaDetails", Namespace="http://schemas.nhn.no/reg/CollaborationProtocolProfile")]
    internal partial class CpaDetails : object
    {
        
        private Helsenorge.Registries.CPAService.CollaborationProtocolAgreement CollaborationProtocolAgreementField;
        
        private Helsenorge.Registries.CPAService.Code StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Helsenorge.Registries.CPAService.CollaborationProtocolAgreement CollaborationProtocolAgreement
        {
            get
            {
                return this.CollaborationProtocolAgreementField;
            }
            set
            {
                this.CollaborationProtocolAgreementField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Helsenorge.Registries.CPAService.Code Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CollaborationProtocolAgreement", Namespace="http://schemas.nhn.no/reg/CollaborationProtocolProfile")]
    internal partial class CollaborationProtocolAgreement : object
    {
        
        private bool ApprovedByPartyAField;
        
        private bool ApprovedByPartyBField;
        
        private System.DateTime CreatedOnField;
        
        private System.Guid IdField;
        
        private Helsenorge.Registries.CPAService.PartyInfo PartyAField;
        
        private Helsenorge.Registries.CPAService.PartyInfo PartyBField;
        
        private System.Nullable<System.DateTime> RevokedField;
        
        private System.DateTime ValidFromField;
        
        private System.DateTime ValidToField;
        
        private string VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ApprovedByPartyA
        {
            get
            {
                return this.ApprovedByPartyAField;
            }
            set
            {
                this.ApprovedByPartyAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ApprovedByPartyB
        {
            get
            {
                return this.ApprovedByPartyBField;
            }
            set
            {
                this.ApprovedByPartyBField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Helsenorge.Registries.CPAService.PartyInfo PartyA
        {
            get
            {
                return this.PartyAField;
            }
            set
            {
                this.PartyAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Helsenorge.Registries.CPAService.PartyInfo PartyB
        {
            get
            {
                return this.PartyBField;
            }
            set
            {
                this.PartyBField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Revoked
        {
            get
            {
                return this.RevokedField;
            }
            set
            {
                this.RevokedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ValidFrom
        {
            get
            {
                return this.ValidFromField;
            }
            set
            {
                this.ValidFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ValidTo
        {
            get
            {
                return this.ValidToField;
            }
            set
            {
                this.ValidToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CpaXmlDetails", Namespace="http://schemas.nhn.no/reg/CollaborationProtocolProfile")]
    internal partial class CpaXmlDetails : object
    {
        
        private string CollaborationProtocolAgreementXmlField;
        
        private Helsenorge.Registries.CPAService.Code StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollaborationProtocolAgreementXml
        {
            get
            {
                return this.CollaborationProtocolAgreementXmlField;
            }
            set
            {
                this.CollaborationProtocolAgreementXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Helsenorge.Registries.CPAService.Code Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessParameter", Namespace="http://schemas.datacontract.org/2004/07/NHN.Palantir.WebServices.Contracts.CPPA.D" +
        "ata")]
    internal partial class ProcessParameter : object
    {
        
        private int HerIdField;
        
        private string NameField;
        
        private Helsenorge.Registries.CPAService.ProcessWithGuid ProcessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HerId
        {
            get
            {
                return this.HerIdField;
            }
            set
            {
                this.HerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Helsenorge.Registries.CPAService.ProcessWithGuid Process
        {
            get
            {
                return this.ProcessField;
            }
            set
            {
                this.ProcessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessWithGuid", Namespace="http://schemas.datacontract.org/2004/07/NHN.Palantir.WebServices.Contracts.CPPA.D" +
        "ata")]
    internal partial class ProcessWithGuid : object
    {
        
        private Helsenorge.Registries.CPAService.Channel[] ChannelsField;
        
        private System.Guid GuidField;
        
        private Helsenorge.Registries.CPAService.Role[] RolesField;
        
        private string VersionNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Helsenorge.Registries.CPAService.Channel[] Channels
        {
            get
            {
                return this.ChannelsField;
            }
            set
            {
                this.ChannelsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Guid
        {
            get
            {
                return this.GuidField;
            }
            set
            {
                this.GuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Helsenorge.Registries.CPAService.Role[] Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VersionNumber
        {
            get
            {
                return this.VersionNumberField;
            }
            set
            {
                this.VersionNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Channel", Namespace="http://schemas.datacontract.org/2004/07/NHN.Palantir.WebServices.Contracts.CPPA.D" +
        "ata")]
    internal partial class Channel : object
    {
        
        private string AddressField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/NHN.Palantir.WebServices.Contracts.CPPA.D" +
        "ata")]
    internal partial class Role : object
    {
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.nhn.no/reg/CollaborationProtocolProfile", ConfigurationName="Helsenorge.Registries.CPAService.ICPPAService")]
    internal interface ICPPAService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetCppForComm" +
            "unicationParty", ReplyAction="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetCppForComm" +
            "unicationPartyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Helsenorge.Registries.CPAService.GenericFault), Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetCppForComm" +
            "unicationPartyGenericFaultFault", Name="GenericFault", Namespace="http://register.nhn.no/Common")]
        System.Threading.Tasks.Task<Helsenorge.Registries.CPAService.CollaborationProtocolProfile> GetCppForCommunicationPartyAsync(int herId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetCppXmlForC" +
            "ommunicationParty", ReplyAction="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetCppXmlForC" +
            "ommunicationPartyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Helsenorge.Registries.CPAService.GenericFault), Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetCppXmlForC" +
            "ommunicationPartyGenericFaultFault", Name="GenericFault", Namespace="http://register.nhn.no/Common")]
        System.Threading.Tasks.Task<string> GetCppXmlForCommunicationPartyAsync(int herId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetAllCollabo" +
            "rationRoles", ReplyAction="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetAllCollabo" +
            "rationRolesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Helsenorge.Registries.CPAService.GenericFault), Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetAllCollabo" +
            "rationRolesGenericFaultFault", Name="GenericFault", Namespace="http://register.nhn.no/Common")]
        System.Threading.Tasks.Task<Helsenorge.Registries.CPAService.CollaborationRole[]> GetAllCollaborationRolesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetCpa", ReplyAction="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetCpaRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(Helsenorge.Registries.CPAService.GenericFault), Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetCpaGeneric" +
            "FaultFault", Name="GenericFault", Namespace="http://register.nhn.no/Common")]
        System.Threading.Tasks.Task<Helsenorge.Registries.CPAService.CpaDetails> GetCpaAsync(System.Guid cpaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetCpaXml", ReplyAction="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetCpaXmlResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Helsenorge.Registries.CPAService.GenericFault), Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetCpaXmlGene" +
            "ricFaultFault", Name="GenericFault", Namespace="http://register.nhn.no/Common")]
        System.Threading.Tasks.Task<Helsenorge.Registries.CPAService.CpaXmlDetails> GetCpaXmlAsync(System.Guid cpaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetCpaForComm" +
            "unicationParties", ReplyAction="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetCpaForComm" +
            "unicationPartiesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Helsenorge.Registries.CPAService.GenericFault), Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetCpaForComm" +
            "unicationPartiesGenericFaultFault", Name="GenericFault", Namespace="http://register.nhn.no/Common")]
        System.Threading.Tasks.Task<Helsenorge.Registries.CPAService.CpaDetails> GetCpaForCommunicationPartiesAsync(int communicationPartAHerId, int communicationPartBHerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetCpaForComm" +
            "unicationPartiesXml", ReplyAction="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetCpaForComm" +
            "unicationPartiesXmlResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Helsenorge.Registries.CPAService.GenericFault), Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetCpaForComm" +
            "unicationPartiesXmlGenericFaultFault", Name="GenericFault", Namespace="http://register.nhn.no/Common")]
        System.Threading.Tasks.Task<Helsenorge.Registries.CPAService.CpaXmlDetails> GetCpaForCommunicationPartiesXmlAsync(int communicationPartAHerId, int communicationPartBHerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetCpasForCom" +
            "municationParty", ReplyAction="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetCpasForCom" +
            "municationPartyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Helsenorge.Registries.CPAService.GenericFault), Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetCpasForCom" +
            "municationPartyGenericFaultFault", Name="GenericFault", Namespace="http://register.nhn.no/Common")]
        System.Threading.Tasks.Task<Helsenorge.Registries.CPAService.CpaDetails[]> GetCpasForCommunicationPartyAsync(int herId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/RevokeCpa", ReplyAction="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/RevokeCpaResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Helsenorge.Registries.CPAService.GenericFault), Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/RevokeCpaGene" +
            "ricFaultFault", Name="GenericFault", Namespace="http://register.nhn.no/Common")]
        System.Threading.Tasks.Task<Helsenorge.Registries.CPAService.CpaDetails> RevokeCpaAsync(System.Guid cpaId, int herId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/AddProcessToC" +
            "pp", ReplyAction="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/AddProcessToC" +
            "ppResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Helsenorge.Registries.CPAService.GenericFault), Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/AddProcessToC" +
            "ppGenericFaultFault", Name="GenericFault", Namespace="http://register.nhn.no/Common")]
        System.Threading.Tasks.Task AddProcessToCppAsync(Helsenorge.Registries.CPAService.ProcessParameter processParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/RemoveProcess" +
            "FromCpp", ReplyAction="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/RemoveProcess" +
            "FromCppResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Helsenorge.Registries.CPAService.GenericFault), Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/RemoveProcess" +
            "FromCppGenericFaultFault", Name="GenericFault", Namespace="http://register.nhn.no/Common")]
        System.Threading.Tasks.Task RemoveProcessFromCppAsync(Helsenorge.Registries.CPAService.ProcessParameter processParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetProcessesI" +
            "nCpp", ReplyAction="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetProcessesI" +
            "nCppResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Helsenorge.Registries.CPAService.GenericFault), Action="http://schemas.nhn.no/reg/CollaborationProtocolProfile/ICPPAService/GetProcessesI" +
            "nCppGenericFaultFault", Name="GenericFault", Namespace="http://register.nhn.no/Common")]
        System.Threading.Tasks.Task<Helsenorge.Registries.CPAService.ProcessParameter[]> GetProcessesInCppAsync(int herId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal interface ICPPAServiceChannel : Helsenorge.Registries.CPAService.ICPPAService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    internal partial class CPPAServiceClient : System.ServiceModel.ClientBase<Helsenorge.Registries.CPAService.ICPPAService>, Helsenorge.Registries.CPAService.ICPPAService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CPPAServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CPPAServiceClient.GetBindingForEndpoint(endpointConfiguration), CPPAServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CPPAServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CPPAServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CPPAServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CPPAServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CPPAServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Helsenorge.Registries.CPAService.CollaborationProtocolProfile> GetCppForCommunicationPartyAsync(int herId)
        {
            return base.Channel.GetCppForCommunicationPartyAsync(herId);
        }
        
        public System.Threading.Tasks.Task<string> GetCppXmlForCommunicationPartyAsync(int herId)
        {
            return base.Channel.GetCppXmlForCommunicationPartyAsync(herId);
        }
        
        public System.Threading.Tasks.Task<Helsenorge.Registries.CPAService.CollaborationRole[]> GetAllCollaborationRolesAsync()
        {
            return base.Channel.GetAllCollaborationRolesAsync();
        }
        
        public System.Threading.Tasks.Task<Helsenorge.Registries.CPAService.CpaDetails> GetCpaAsync(System.Guid cpaId)
        {
            return base.Channel.GetCpaAsync(cpaId);
        }
        
        public System.Threading.Tasks.Task<Helsenorge.Registries.CPAService.CpaXmlDetails> GetCpaXmlAsync(System.Guid cpaId)
        {
            return base.Channel.GetCpaXmlAsync(cpaId);
        }
        
        public System.Threading.Tasks.Task<Helsenorge.Registries.CPAService.CpaDetails> GetCpaForCommunicationPartiesAsync(int communicationPartAHerId, int communicationPartBHerId)
        {
            return base.Channel.GetCpaForCommunicationPartiesAsync(communicationPartAHerId, communicationPartBHerId);
        }
        
        public System.Threading.Tasks.Task<Helsenorge.Registries.CPAService.CpaXmlDetails> GetCpaForCommunicationPartiesXmlAsync(int communicationPartAHerId, int communicationPartBHerId)
        {
            return base.Channel.GetCpaForCommunicationPartiesXmlAsync(communicationPartAHerId, communicationPartBHerId);
        }
        
        public System.Threading.Tasks.Task<Helsenorge.Registries.CPAService.CpaDetails[]> GetCpasForCommunicationPartyAsync(int herId)
        {
            return base.Channel.GetCpasForCommunicationPartyAsync(herId);
        }
        
        public System.Threading.Tasks.Task<Helsenorge.Registries.CPAService.CpaDetails> RevokeCpaAsync(System.Guid cpaId, int herId)
        {
            return base.Channel.RevokeCpaAsync(cpaId, herId);
        }
        
        public System.Threading.Tasks.Task AddProcessToCppAsync(Helsenorge.Registries.CPAService.ProcessParameter processParameter)
        {
            return base.Channel.AddProcessToCppAsync(processParameter);
        }
        
        public System.Threading.Tasks.Task RemoveProcessFromCppAsync(Helsenorge.Registries.CPAService.ProcessParameter processParameter)
        {
            return base.Channel.RemoveProcessFromCppAsync(processParameter);
        }
        
        public System.Threading.Tasks.Task<Helsenorge.Registries.CPAService.ProcessParameter[]> GetProcessesInCppAsync(int herId)
        {
            return base.Channel.GetProcessesInCppAsync(herId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICPPAService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_ICPPAService))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICPPAService))
            {
                return new System.ServiceModel.EndpointAddress("https://register-web.test.nhn.no/v1/CPPA/Basic");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_ICPPAService))
            {
                return new System.ServiceModel.EndpointAddress("https://register-web.test.nhn.no/v1/CPPA");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICPPAService,
            
            WSHttpBinding_ICPPAService,
        }
    }
}
