name: Build and test

on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ windows-latest, ubuntu-latest, macos-14 ]
    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json
    - name: Install dependencies
      run: dotnet restore Messaging.slnx
    - name: Build
      run: dotnet build Messaging.slnx --configuration Release --no-restore
    - name: Unit tests
      run: |
        dotnet test "./test/Helsenorge.Messaging.Tests/Helsenorge.Messaging.Tests.csproj"
        dotnet test "./test/Helsenorge.Registries.Tests/Helsenorge.Registries.Tests.csproj"
        dotnet test "./test/Helsenorge.Messaging.AdminLib.Tests/Helsenorge.Messaging.AdminLib.Tests.csproj"
